In [1]:
import pandas as pd

In [2]:
df =pd.read_csv('data.csv')

In [3]:
df.head(10)

Fever  bodypain  age  runnynose  difbreathe  prbabilty
0    104         1   50          1           1          1
1     98         0    9          0           1          1
2    101         0   50          1           1          1
3    102         0   71          1          -1          1
4     98         0   36          1          -1          1
5     99         0   32          0           1          0
6    103         1    3          0          -1          0
7    101         0   65          0           0          0
8    104         1   24          1           0          1
9    104         1    2          0          -1          1

In [4]:
df.tail()

Fever  bodypain  age  runnynose  difbreathe  prbabilty
2662    101         0   41          0           0          1
2663    104         0   68          0           0          0
2664    103         0   24          0           0          1
2665    103         0   51          1           1          0
2666    104         0   44          0           1          0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2667 entries, 0 to 2666
Data columns (total 6 columns):
Fever         2667 non-null int64
bodypain      2667 non-null int64
age           2667 non-null int64
runnynose     2667 non-null int64
difbreathe    2667 non-null int64
prbabilty     2667 non-null int64
dtypes: int64(6)
memory usage: 125.1 KB


In [6]:
df['difbreathe'].value_counts()

 0    920
 1    882
-1    865
Name: difbreathe, dtype: int64

In [7]:
df.describe()

Fever     bodypain         age    runnynose   difbreathe  \
count  2667.000000  2667.000000  2667.00000  2667.000000  2667.000000   
mean    101.040495     0.491189    49.96213     0.499438     0.006374   
std       1.981121     0.500016    28.70282     0.500093     0.809474   
min      98.000000     0.000000     1.00000     0.000000    -1.000000   
25%      99.000000     0.000000    25.00000     0.000000    -1.000000   
50%     101.000000     0.000000    51.00000     0.000000     0.000000   
75%     103.000000     1.000000    75.00000     1.000000     1.000000   
max     104.000000     1.000000   100.00000     1.000000     1.000000   

         prbabilty  
count  2667.000000  
mean      0.504312  
std       0.500075  
min       0.000000  
25%       0.000000  
50%       1.000000  
75%       1.000000  
max       1.000000

In [8]:
import numpy as np

In [9]:
def data_split(data,ratio):
       np.random.seed(42)
       shuffled =np.random.permutation(len(data))
       test_set_size=int(len(data)*ratio)
       test_indices=shuffled[:test_set_size]
       train_indices=shuffled[test_set_size:]
       return data.iloc[train_indices], data.iloc[test_indices] 
    

In [10]:
np.random.permutation(8)

array([0, 2, 4, 1, 3, 6, 7, 5])

In [11]:
train, test =data_split(df, 0.2)

In [12]:
train

Fever  bodypain  age  runnynose  difbreathe  prbabilty
1907     99         0   12          0          -1          0
867     101         1    3          0          -1          0
1640    102         0   37          1          -1          1
544      98         0   56          0          -1          1
1562    104         1   33          1           0          0
...     ...       ...  ...        ...         ...        ...
1638     98         1   82          1           0          0
1095     98         1   97          0          -1          1
1130    103         0   55          0           1          0
1294    101         1   51          1          -1          0
860     100         0   68          1          -1          0

[2134 rows x 6 columns]

In [13]:
test

Fever  bodypain  age  runnynose  difbreathe  prbabilty
298     101         0    6          1           0          0
1809    100         0   73          0           1          1
1575    101         1   61          0           1          1
2447    103         1   35          1          -1          1
929     101         1    1          0          -1          1
...     ...       ...  ...        ...         ...        ...
1187     99         0   51          1          -1          0
2004    101         0   23          0           1          0
986     102         1   71          0           1          1
69      100         0   85          0           1          1
1667    102         1   46          1           1          0

[533 rows x 6 columns]

In [14]:
X_train = train[['Fever', 'bodypain', 'age', 'runnynose', 'difbreathe']].to_numpy()
X_train = train[['Fever', 'bodypain', 'age', 'runnynose', 'difbreathe']].to_numpy()

In [15]:
X_train

array([[ 99,   0,  12,   0,  -1],
       [101,   1,   3,   0,  -1],
       [102,   0,  37,   1,  -1],
       ...,
       [103,   0,  55,   0,   1],
       [101,   1,  51,   1,  -1],
       [100,   0,  68,   1,  -1]], dtype=int64)

In [16]:
Y_train = train[['prbabilty']].to_numpy().reshape(2134,)
Y_test =test[['prbabilty']].to_numpy().reshape(533,)

In [17]:
Y_train

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
clf = LogisticRegression()
clf.fit(X_train,Y_train)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [31]:
inputFeatures =[104, 1, 90, 1, 1]
infProb =clf.predict_proba([inputFeatures])[0][1]

In [32]:
infProb

0.5237838858305893